# golangci-lint configuration (YAML format for compatibility)
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .git
    - .github

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - whitespace
    - gocritic
    - gocyclo
    - lll
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    
  govet:
    check-shadowing: true
    
  gocyclo:
    min-complexity: 15
    
  misspell:
    locale: US
    
  lll:
    line-length: 120
    
  goimports:
    local-prefixes: github.com/tokuhirom/vrrp-simple
    
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - paramTypeCombine
      - whyNoLint
      - commentedOutCode
      
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        
    - path: test/
      linters:
        - errcheck
        
  max-issues-per-linter: 50
  max-same-issues: 10