version: '3.8'

services:
  vrrp1:
    build: .
    container_name: vrrp1
    hostname: vrrp1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      vrrpnet:
        ipv4_address: 172.30.0.10
    environment:
      - VRRP_INTERFACE=eth0
      - VRRP_VRID=10
      - VRRP_PRIORITY=150
      - VRRP_VIP=172.30.0.100
    command: >
      run
      --interface eth0
      --vrid 10
      --priority 150
      --vips 172.30.0.100
    restart: unless-stopped

  vrrp2:
    build: .
    container_name: vrrp2
    hostname: vrrp2
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      vrrpnet:
        ipv4_address: 172.30.0.11
    environment:
      - VRRP_INTERFACE=eth0
      - VRRP_VRID=10
      - VRRP_PRIORITY=100
      - VRRP_VIP=172.30.0.100
    command: >
      run
      --interface eth0
      --vrid 10
      --priority 100
      --vips 172.30.0.100
    restart: unless-stopped

  # Optional: monitoring container
  monitor:
    image: nicolaka/netshoot:latest
    container_name: vrrp-monitor
    hostname: monitor
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      vrrpnet:
        ipv4_address: 172.30.0.20
    command: >
      sh -c "
      while true; do
        echo '=== VRRP Status ===' &&
        date &&
        ping -c 1 -W 1 172.30.0.100 >/dev/null 2>&1 &&
        echo 'VIP 172.30.0.100 is reachable' ||
        echo 'VIP 172.30.0.100 is NOT reachable' &&
        echo '' &&
        sleep 5
      done
      "
    restart: unless-stopped

networks:
  vrrpnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1