name: Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Run unit tests
        run: go test -v -race -coverprofile=coverage.txt ./...
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          flags: unittests

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            iproute2 \
            bridge-utils \
            tcpdump \
            iputils-ping
      
      - name: Build VRRP binary
        run: go build -o vrrp ./main.go
      
      - name: Run integration tests
        run: |
          sudo chmod +x test/integration/scripts/*.sh
          sudo ./test/integration/scripts/run_integration_tests.sh
      
      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: |
            test/integration/*.log
            /tmp/vrrp-test-*.log

  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t vrrp-simple:test .
        continue-on-error: true
      
      - name: Run Docker Compose tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose -f docker-compose.test.yml up --abort-on-container-exit
          else
            echo "Docker Compose test file not found, skipping"
          fi
        continue-on-error: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=5m
          skip-cache: false
          skip-pkg-cache: false
          skip-build-cache: false

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
        continue-on-error: true
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
        continue-on-error: true